[package]
name = "one_key_pcmidi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
apres = "0.3.4"
symphonia = { version = "0.5.1", features = ["mp3", "aac"] }
